services:
  brandtoon_postgres:
    container_name: "brandtoon_postgres"
    restart: always
    image: postgres:18
    # volumes:
    #   - postgres-data:/var/lib/postgresql/docker
    environment:
      POSTGRES_USER: brandtoon
      POSTGRES_PASSWORD: brandtoon
      POSTGRES_DB: brandtoon
    ports:
      - "5432:5432"
